spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/clo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 최초 1회 create하고 삭제해야 함.
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug